### ISSUE TITLE
PIL.UnidentifiedImageError on HEIF file despite pyheif-pillow-opener

### ISSUE THREAD

**Issue by mara004** [ciotto/pyheif-pillow-opener#6]
I tried to use pyheif_pillow_opener, but can't get it to work.

```python3
>>> from PIL import Image
>>> from pyheif_pillow_opener import register_heif_opener
>>> register_heif_opener()
>>> img = Image.open(".../heif.heic")
...
PIL.UnidentifiedImageError: cannot identify image file
```

The test file is available [here](https://github.com/mara004/testfiles/blob/main/heif_image.heic).
I'm using a Ubuntu 20.04 derivative, pyheif 0.5.1, libheif1 1.11.0, and libde265-0 1.0.8.

(Initially posted at https://github.com/python-pillow/Pillow/issues/2806#issuecomment-938587205)

**Comment by homm** [comment]
I have no problems with this image with pyheif 0.5.1, libheif1 1.11.0 and recent versions. Try following to find actual reason:

```python
import pyheif
pyheif.read('./heif_image.heic')
```

**Comment by mara004** [comment]
Pyheif says:
```python3
>>> pyheif.read(TestFiles.heif)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mara/.local/lib/python3.8/site-packages/pyheif/reader.py", line 37, in read
    result = _read_heif_bytes(d, apply_transformations, convert_hdr_to_8bit)
  File "/home/mara/.local/lib/python3.8/site-packages/pyheif/reader.py", line 72, in _read_heif_bytes
    result = _read_heif_context(ctx, d, apply_transformations, convert_hdr_to_8bit)
  File "/home/mara/.local/lib/python3.8/site-packages/pyheif/reader.py", line 100, in _read_heif_context
    result = _read_heif_handle(handle, apply_transformations, convert_hdr_to_8bit)
  File "/home/mara/.local/lib/python3.8/site-packages/pyheif/reader.py", line 135, in _read_heif_handle
    raise _error.HeifError(
pyheif.error.HeifError: Code: 4, Subcode: 3003, Message: "Unsupported feature: Unsupported color conversion"
```
